const generateConfig = {
  moduleName: "Checkin",
  routeVersion: "v1",
  parameters: [
    {
      name: "driver",
      sensitive: false,
      ref: "driver",
      type: "String",
      isUploadable: false,
      isRequired: true,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "vehicle",
      sensitive: false,
      type: "String",
      ref: "vehicle",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "store",
      sensitive: false,
      type: "String",
      ref: "store",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "date",
      sensitive: false,
      type: "Date",
      isUploadable: false,
      isRequired: true,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "store_checkin_time",
      sensitive: false,
      type: "Date",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "vehicle_checkin_time",
      sensitive: false,
      type: "Date",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "vehicle_pickup_images",
      sensitive: false,
      type: "String",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "vehicle_drop_images",
      sensitive: false,
      type: "String",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "store_checkout_time",
      sensitive: false,
      type: "Date",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "vehicle_checkout_time",
      sensitive: false,
      type: "Date",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
  ],
};

module.exports = generateConfig;
