const generateConfig = {
  moduleName: "Organization",
  routeVersion: "v1",
  parameters: [
    {
      name: "name",
      sensitive: false,
      type: "String",
      isUploadable: false,
      isRequired: true,
      isSearchable: true,
      isEditable: true,
    },
    {
      name: "logo",
      sensitive: false,
      type: "String",
      isUploadable: true,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "gst",
      sensitive: false,
      type: "String",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "gst_doc",
      sensitive: false,
      type: "String",
      isUploadable: true,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "cancelled_cheque",
      sensitive: false,
      type: "String",
      isUploadable: true,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "pan_card",
      sensitive: false,
      type: "String",
      isUploadable: true,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "price_per_order",
      sensitive: false,
      type: "Number",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },{
      name: "minimum_guarentee",
      sensitive: false,
      type: "Number",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "price_over_order",
      sensitive: false,
      type: "Number",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "category",
      sensitive: false,
      type: "String",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "contract_period",
      sensitive: false,
      type: "String",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "agreement",
      sensitive: false,
      type: "String",
      isUploadable: true,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "driver_price_per_order",
      sensitive: false,
      type: "Number",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "driver_minimum_guarentee",
      sensitive: false,
      type: "Number",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "driver_price_over_order",
      sensitive: false,
      type: "Number",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
  ]
}

module.exports = generateConfig;