const generateConfig = {
  moduleName: 'Store',
  routeVersion: 'v1',
  parameters: [
    {
      name: 'name',
      sensitive: false,
      type: 'String',
      isUploadable: false,
      isRequired: true,
      isSearchable: true,
      isEditable: true,
    },
    {
      name: 'address',
      sensitive: false,
      type: 'String',
      ref: 'address',
      isUploadable: false,
      isRequired: true,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: 'type',
      sensitive: false,
      type: 'String',
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: 'phone',
      sensitive: false,
      type: 'String',
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: 'store_incharge',
      sensitive: false,
      type: 'String',
      ref: 'user',
      isUploadable: false,
      isRequired: true,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: 'organization',
      sensitive: false,
      type: 'String',
      ref: 'organization',
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
  ],
};

module.exports = generateConfig;
