const generateConfig = {
  moduleName: "Vehicle",
  routeVersion: "v1",
  parameters: [
    {
      name: "model",
      sensitive: false,
      type: "String",
      isUploadable: false,
      isRequired: true,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "number",
      sensitive: false,
      type: "String",
      isUploadable: false,
      isRequired: true,
      isSearchable: true,
      isEditable: true,
    },
    {
      name: "type",
      sensitive: false,
      type: "String",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "bike_image",
      sensitive: false,
      type: "String",
      isUploadable: true,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "charge_percentage",
      sensitive: false,
      type: "Number",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "total_kms",
      sensitive: false,
      type: "Number",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "id",
      sensitive: false,
      type: "Number",
      isUploadable: false,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "rc_book_image",
      sensitive: false,
      type: "String",
      isUploadable: true,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
    {
      name: "insurance_image",
      sensitive: false,
      type: "String",
      isUploadable: true,
      isRequired: false,
      isSearchable: false,
      isEditable: true,
    },
  ]
}

module.exports = generateConfig;