export enum BOOKING {
  PLACED = "PLACED",
  ACCEPTED = "ACCEPTED",
  PICKED_UP= "PICKED UP",
  DELIVERED= "DELIVERED",
  CANCELLED= "CANCELLED",
  REJECTED= "REJECTED",
};

export enum BOOKING_FILTER {
  LIVE = "LIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  MANUAL = "MANUAL",
  ALL = "ALL",
}

export enum PAYMENT_TYPE {
  COD = "COD",
}