export const TEST_ACTION = "TEST_ACTION";
export const CONVERSATION = "CONVERSATION";

// ORGANIZATION
export const GET_ORGANIZATION = "GET_ORGANIZATION"
export const GET_MANY_ORGANIZATION = "GET_MANY_ORGANIZATION"

export const GET_USER = "GET_USER"
export const GET_MANY_USER = "GET_MANY_USER";
export const GET_VEHICLE = "GET_VEHICLE"
export const GET_MANY_VEHICLE = "GET_MANY_VEHICLE";
export const GET_STORES = "GET_STORES"
export const GET_MANY_STORES = "GET_MANY_STORES";
export const GET_HUB = "GET_HUB"
export const GET_MANY_HUB = "GET_MANY_HUB";
export const GET_OUTSOURCE = "GET_OUTSOURCE"
export const GET_MANY_OUTSOURCE = "GET_MANY_OUTSOURCE";
export const GET_PAYOUT = "GET_PAYOUT"
export const GET_MANY_PAYOUT = "GET_MANY_PAYOUT";
export const GET_DRIVER = "GET_DRIVER"
export const GET_MANY_DRIVER = "GET_MANY_DRIVER";
export const GET_BOOKING = "GET_BOOKING"
export const GET_MANY_BOOKING = "GET_MANY_BOOKING";

export const SET_ADDRESS_QUERY = "SET_ADDRESS_QUERY"
export const SET_STORE_QUERY = "SET_STORE_QUERY"
export const SET_ORGANIZATION_QUERY = "SET_ORGANIZATION_QUERY"
export const SET_DRIVER_QUERY = "SET_DRIVER_QUERY"
export const SET_VEHICLE_QUERY = "SET_VEHICLE_QUERY"
export const SET_USER_QUERY = "SET_USER_QUERY"

export const GET_CHECKIN = "GET_CHECKIN"
export const GET_MANY_CHECKIN = "GET_MANY_CHECKIN";
// _RT_
